* About
[[https://shaunlebron.github.io/parinfer/][Parinfer]]'s goal is to simplify how lisp is written and appeal to newcomers. It does this by using indentation-based inference to properly balance parentheses and allow for convenient functionality without requiring the use of any complicated keybindings. It currently has about as many stars on github as both [[https://github.com/abo-abo/lispy][lispy]] and [[https://github.com/Fuco1/smartparens][smartparens]] combined.

I think parinfer is an interesting idea, and the fact that there are many implementations for various editors may make it a good starting point for those new to writing lisp (those who never try using emacs for writing lisp will probably miss out on a lot of functionality though).

However, I think that its biggest flaw is also its core principle. With indentation-based inference, the location of parentheses is fragile and waiting to be unknowingly broken. This requires the user to manually re-indent or know when to change to parinfer's other mode of operation. Unless parinfer can somehow manage to automate this switching, I think that the cognitive load of having to know when parinfer's "indent mode" will break your code is not worth a potentially easier implementation (more on this later). Even if there is some way to mitigate this problem, I imagine that it would complicate the implementation sufficiently to prevent it from being any better than foregoing indentation-based inference altogether. Here I will show that all of parinfer's example functionality can be implemented without burdening the user in this way and while still sticking to the same simple keypresses.

Examples here are currently done with multiple plugins. This is not ideal. It is just meant to be proof that all the benefits parinfer gives do not require having distinct "indent" and "paren" modes. As no indentation-based inference is used, examples will be done in what is closer to parinfer's "paren" mode.

* Downsides of Parinfer
Parinfer determines where parentheses should go based on the code's indentation. For the most part, it gets around requiring manual indentation by auto-indenting to the correct position when hitting enter. However, any time you change the indentation (or even line length in some cases!) after the initial auto-indentation happens, you will have to manually re-indent. If you don't want to manually re-indent everything yourself, you must switch to parinfer's "paren mode", make the change, and then switch back to "indent mode."

For example, if you wanted to bring a sexp up to the preceding line in "indent mode", you would either have to backspace to the beginning of the line and then backspace through every closing paren or use the mouse to select the area you want to delete:

[[moving a sexp up][file:parinfer_demos/parinfer-downsides-1.gif]]

[[moving a sexp up with the mouse][file:parinfer_demos/parinfer-downsides-2.gif]]

In emacs, this would only require a single press of backspace. In the demo boxes, parinfer's "paren mode" still requires either spamming backspace or using the mouse. This could be changed to only require a single backspace, but it still would require two presses of some modifier keybinding (which parinfer claims it wants to avoid) to get in and out of "paren mode." Also, in "paren mode" you get none of the benefits you would normally have with something like paredit or smartparens. There is no auto-closing, for example, and parinfer's nice features won't work. It won't ensure that your parentheses are balanced either. These features could be added to "paren mode" to make it better, but the features "indent mode" gives can be implemented without the need for indentation-based inference in the first place.

Furthermore, parinfer will mess up your code in certain cases, even when you're not changing the indentation at the beginning of a line:

[[indentation-based inference][file:parinfer_demos/parinfer-downsides-3.gif]]

Parinfer will also work incorrectly if you have unbalanced quotes in a comment.

These limitations mean that you have to know exactly when parinfer will break your code or at least pay careful attention to catch when it does so that you can undo your changes and then redo them in "paren mode." Is this really something a beginner should be expected to cope with?

With the normal way of editing (no indentation based inference), your code can always be correctly indented (see [[https://github.com/Malabarba/aggressive-indent-mode][aggressive-indent]]). Parentheses won't disappear and appear all the time and will never be moved to different spots unless you explicitly tell them to.

You can see [[https://shaunlebron.github.io/parinfer/#paren-mode][here]] for other examples of where parinfer's "indent mode" fails to have the desired behavior.

** Other Notes
Parinfer will fix incorrect indentation when reading a file. I don't really consider this to be a downside, but parinfer does list it as one. I do wonder how parinfer reacts to code with tabs and spaces though.

* Benefits of Parinfer
Parinfer claims the following:
#+BEGIN_QUOTE
Inferring parentheses based on indentation seems to lead to simpler editing mechanics for Lisp code. It leads to a system that keeps our code formatted well. And it allows us to use paredit-like features without hotkeys.

I think the biggest win is its potential to quell fear of managing end-of-line parens by enforcing a direct driving relationship with indentation.
#+END_QUOTE

I will show that all of this can be achieved without any of parinfer's methods and consequently without its downsides. As far as I am aware, there are no benefits that the parinfer method has for the user. However, to the implementer, parinfer may be simpler (I mention more about this in specific examples).

* Gears
Parinfer has some pretty [[https://shaunlebron.github.io/parinfer/#tools-for-writing-lisp][diagrams of gears]] representing the relationship between indentation and parentheses. It claims the following:
#+BEGIN_QUOTE
Existing tools automate some of these editing tasks. For example, Paredit forces you to transform or add parens in a balanced way through special hotkeys. And Auto-indent allows you to auto-correct indentation of selected lines when desired. This automates the tasks, but the back-and-forth actions are still manually triggered.
#+END_QUOTE

This is completely false. Again, refer to [[https://github.com/Malabarba/aggressive-indent-mode][aggressive-indent]] which will automatically correct indentation without ever requiring the user to manually hit a key
. The parinfer page even mentions aggressive-indent, so I don't know why it ignores it here.

Parinfer also claims the following:
#+BEGIN_QUOTE
Parinfer is a new tool to combine and simplify this type of automation by naturally keeping Parens and Indentation in lockstep. It formally infers changes to one based on the other. The back-and-forth actions have been reduced with special modes, which we will explore next.
#+END_QUOTE

As stated in the last section, I will give examples showing that either parentheses or indentation can be changed *without* the need to have two distinct modes. You can think of this as being able to spin either gear without having to switch contexts.

* Parinfer Examples Done Without Need for Two Distinct Modes
The demos I will be referring to can be found [[https://shaunlebron.github.io/parinfer/][here]].

Note that for the first examples, parinfer does it in more keypresses than necessary by first moving the point to the beginning of the line. Parinfer will actually preserve the current scope when you hit enter normally. It also allows you to change scope by pressing =)= to move the point past a closing paren much like you would in emacs.

** Rearrange Parens with Indentation
[[rearrange parens][file:emacs_demos/rearrange-parens.gif]]

This is done using the =adjust-parens= emacs plugin. This can also be done in reverse. Smartparens also has commands called ~sp-indent-adjust-sexp~ and ~sp-dedent-adjust-sexp~ that do the same thing.

*** Notes on Differences
Neither emacs package supports the selection part by default, so I used evil's visual column mode to show that it is possible to indent and adjust parens for multiple sexps at once. This is why you see the delay between the first =[]= block being indented and the second =[]= block being indented to the same level. I imagine that this would also work with multiple cursors. Ideally, this would be done in one step.

Also, unlike with parinfer, this method requires the use of tab and shift+tab to change indentation. I don't see this as a problem since spamming space is more keypresses anyway.

** Insert or Delete a Line Without Rearranging Parens
[[insert a line or delete a region][file:emacs_demos/adding-and-deleting-lines-region.gif]]

The above example shows that a selected region can be deleted without unbalancing parentheses just like in parinfer (without the need for "special hotkeys"). This can be done with [[https://github.com/abo-abo/lispy][lispy]], =evil-cleverparens=, etc.

[[insert or delete a line with evil][file:emacs_demos/adding-and-deleting-lines-evil.gif]]

This second example is done using the [[https://github.com/luxbock/evil-cleverparens][evil-cleverparens]] plugin which allows evil's deleting and changing commands to maintain paren balance (=evil-smartparens= can also be used).

The downside to this approach is that all commands for deleting text must be wrapped to be safe. However, there is no burden on the user (only on the implementer), and all common commands for deletion already have safe versions in emacs (with multiple implementations in the case of evil commands).

** Comment a Line Without Rearranging Parens
[[comment a line][file:emacs_demos/comment-line.gif]]

This uses ~lispy-comment~ which has the same effect except that it only requires one press of =;= to correctly format everything (including adding a space).

** Basic Paredit Without Hotkeys
[[basic paredit without hotkeys][file:emacs_demos/basic-paredit-without-hotkeys.gif]]

In this example, I have bound =DEL= (backspace) to splice before an open paren or to slurp as far as possible before a close paren, =(= to a command that wraps to the end of the line, and =)= to a command that barfs to the point. 

There is nothing about this that requires inference; it is just different keybindings. I also think that the lispy defaults make more sense for =DEL= (deletes the sexp) and =)= (jumps to closing block). The fact that =DEL= slurps when you delete a closing paren in parinfer makes sense knowing how parinfer works, but otherwise it seems very counter-intuitive.

I tried to replicate the parinfer demo by keeping the point after the =+= for the final slurp. I also don't think this is optimal and think it would make more sense to stay with the point after the =)= like how you would normally when slurping in lispy.

See [[https://github.com/abo-abo/lispy][lispy]] for /advanced/ paredit functionality without the need for using complicated keybindings.

*** Notes on Differences
When splicing the =(= before the let, I used an undo operation to get back the surrounding parentheses. The reason the parinfer case slurps as far as possible instead of to the end of the line is because parinfer doesn't automatically update indentation, so it can still infer the same paren placement as before. However, I don't consider this to be an upside of the inference method because I don't see any situation in which it would be useful. For example, your indentation will cause parinfer to wrap to a single location, and if you wanted to wrap to a different location, you would have to manually change the indentation first. An implementation of this in lispy could allow one to easily choose between wrapping to the end of line or as far as possible and still use simple keys (without requiring any indentation changes).

It's also probably worth noting that after this splice, the expression is even more incorrect than it was before, so an undo operation probably makes more sense anyway.

** Preserve indentation
See the [[https://github.com/Malabarba/aggressive-indent-mode#demonstration][demos for aggressive-indent]].

* Final Thoughts
These are the final thoughts listed for parinfer:
#+BEGIN_QUOTE
Regardless of how we choose to edit our Lisp code, there seems to always be a balancing act between maintaining the simplicity of how we interact with the editor and accepting some editor complexity to gain automation over these powerful but numerous parens.

Building the interactive examples for this page has allowed me to explore how well Parinfer can play this balancing act, but only in a demo environment. The real test will come once it becomes available to major editors. See editor plugins for progress.
#+END_QUOTE

I disagree with the conclusion reached. A hypothetical plugin that implemented all of my examples here would have all the benefits listed for parinfer without any of the downsides. The closest thing to this at the moment is [[https://github.com/abo-abo/lispy][lispy]], which also allows for far more advanced editing.
